---
title: "missionboard"
output: 
  flexdashboard::flex_dashboard:
    theme: flatly
    social: menu
    orientation: columns
    vertical_layout: fill
    logo: virtulis-logo.png
    favicon: virtulis-logo.png
---

```{r setup, include=FALSE}

library(twilio)
library(magrittr)

library(flexdashboard)

library(lubridate)
library(dplyr)
library(readr)

library(RGoogleAnalytics)

library(ggplot2)
library(ggstance)
library(ggalt)

library(crimedata)
library(pdfetch)
library(xlsx)

```

```{r}
# Twilio set-up

Sys.setenv(TWILIO_SID = "ACc1af2ca61d9771eaa4f5fecc1c733ee2")
Sys.setenv(TWILIO_TOKEN = "a6dd333f4146c84faedbf707916aab28")

my_phone_number <- "4438573881"
twilio_phone_number <- "6672132931"

tw_send_message(from = twilio_phone_number,
                to = my_phone_number,
                body = "Hello from R")
```

```{r}
# Retrieve sent and received messages log

tw_get_messages_list() %>%
  tw_message_tbl()
```

```{r}
# Retrieve sent and received media attachments log

tw_get_message_media() %>%
  tw_message_tbl()
```

```{r}
data_crime <- get_crime_data()
data_crime
```

```{r}
# data_crime
# Exporting data to a tabl-delimited text file

write.table(data_crime, "/cloud/project/data_exported/data_crime_exported.txt", sep="\t")
```









