if (!require(devtools))
  install.packages("devtools")

devtools::install_github("rstudio/leaflet")
devtools::install_github("hadley/dplyr")
devtools::install_github("cran/plotly")
devtools::install_github("cran/RColorBrewer")
devtools::install_github("hadley/scales")
devtools::install_github("cran/lattice")
devtools::install_github("krlmlr/bindr")

library(RColorBrewer)
library(scales)
library(lattice)
library(dplyr)
library (plotly)
library(leaflet)
library(Shiny)
library(bindr)

shiny::runGitHub("abhishekms1047/Talk-to-R-Shiny")