library(RColorBrewer)
library(scales)
library(lattice)
library(dplyr)
library (plotly)
library(leaflet)
library(shiny)
library(bindr)
library(DT)
library(leaflet)

shiny::runGitHub("MCTTAN/virtulis")
#shiny::runGitHub("abhishekms1047/Talk-to-R-Shiny")